/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException;
import persistencia.cConnection;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Xeride
 */
public class frmFiltroContactos extends javax.swing.JFrame {

    /**
     * Creates new form frmFiltroContactos
     */
    public frmFiltroContactos() {
        initComponents();
        setLocationRelativeTo(null); //Para que aparezca en centro de la pantalla
        MostrarDatos(); //llama la funcion MostrarDatos
        MostrarRegistroTabla(); //llama la funcion MostrarRegistroTabla
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFiltro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnVarones = new javax.swing.JButton();
        btnMujeres = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        tbnRegresar = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblFiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9"
            }
        ));
        jScrollPane1.setViewportView(tblFiltro);

        jLabel1.setText("filtro");

        btnVarones.setText("Varones");
        btnVarones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaronesActionPerformed(evt);
            }
        });

        btnMujeres.setText("Mujeres");
        btnMujeres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMujeresActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione su metodo de filtrado");

        btnLimpiar.setText("Limpiar tabla");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tbnRegresar.setText("Regresar");
        tbnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnRegresarActionPerformed(evt);
            }
        });

        btnMostrarTodo.setText("Mostrar todos los datos");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrarTodo)
                .addGap(31, 31, 31)
                .addComponent(btnLimpiar)
                .addGap(18, 18, 18)
                .addComponent(tbnRegresar)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btnVarones)
                        .addGap(103, 103, 103)
                        .addComponent(btnMujeres))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMujeres)
                    .addComponent(btnVarones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiar)
                    .addComponent(tbnRegresar)
                    .addComponent(btnMostrarTodo))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVaronesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaronesActionPerformed
        Limpiesa();
        try{
            Connection conex = null; //llama la conexion
            DefaultTableModel dTabla = (DefaultTableModel)tblFiltro.getModel();
            cConnection conectando = new cConnection(); //llama la clase cConnection
            conex = conectando.getConnection();//retorna conexion
            String Registro[] = new String[10]; //aca el numero lo modificas segun la cantidad de columnas
            String SQL = "Select * from datos where Genero = 'M' "; //sentencia sql para llamar los registros
            Statement sentencia = conex.createStatement(); //crea la sentencia sql
            ResultSet rst = sentencia.executeQuery(SQL); //ejecuta la consulta de la sentencia sql
            while(rst.next()){
                Registro[0] = rst.getString("DNI"); //el numero y el nombre que esta en tu BD, en este caso access, se comienza desde cero
                Registro[1] = rst.getString("Nombre"); 
                Registro[2] = rst.getString("ApellidoPaterno");
                Registro[3] = rst.getString("ApellidoMaterno");
                Registro[4] = rst.getString("Genero"); 
                Registro[5] = rst.getString("Telefono");
                Registro[6] = rst.getString("Correo");
                Registro[7] = rst.getString("FechaNacimiento");
                Registro[8] = rst.getString("Direccion");
                dTabla.addRow(Registro); //Agrega a cada columna
            }
            tblFiltro.setModel(dTabla); //para llamar nuestra tabla
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Se ha producido un error al cargar los datos - " + e);//mensaje de error y el problema a resolver
        }
    }//GEN-LAST:event_btnVaronesActionPerformed

    private void btnMujeresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMujeresActionPerformed
        Limpiesa();
        try{
            Connection conex = null; //llama la conexion
            DefaultTableModel dTabla = (DefaultTableModel)tblFiltro.getModel();
            cConnection conectando = new cConnection(); //llama la clase cConnection
            conex = conectando.getConnection();//retorna conexion
            String Registro[] = new String[10]; //aca el numero lo modificas segun la cantidad de columnas
            String SQL = "Select * from datos where Genero = 'F' "; //sentencia sql para llamar los registros
            Statement sentencia = conex.createStatement(); //crea la sentencia sql
            ResultSet rst = sentencia.executeQuery(SQL); //ejecuta la consulta de la sentencia sql
            while(rst.next()){
                Registro[0] = rst.getString("DNI"); //el numero y el nombre que esta en tu BD, en este caso access, se comienza desde cero
                Registro[1] = rst.getString("Nombre"); 
                Registro[2] = rst.getString("ApellidoPaterno");
                Registro[3] = rst.getString("ApellidoMaterno");
                Registro[4] = rst.getString("Genero"); 
                Registro[5] = rst.getString("Telefono");
                Registro[6] = rst.getString("Correo");
                Registro[7] = rst.getString("FechaNacimiento");
                Registro[8] = rst.getString("Direccion");
                dTabla.addRow(Registro); //Agrega a cada columna
            }
            tblFiltro.setModel(dTabla); //para llamar nuestra tabla
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Se ha producido un error al cargar los datos - " + e);//mensaje de error y el problema a resolver
        }
    }//GEN-LAST:event_btnMujeresActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiesa();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tbnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnRegresarActionPerformed
        this.setVisible(false);
        new frmMenuPrincipal().setVisible(true);
    }//GEN-LAST:event_tbnRegresarActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        Limpiesa();
        Mostrar();
    }//GEN-LAST:event_btnMostrarTodoActionPerformed
    public void MostrarDatos(){ //Para que no edites los nombre de cada columna de la tabla, si no tienes pereza, editalo tu mismo
        DefaultTableModel MiTabla = (DefaultTableModel)tblFiltro.getModel();
        String EncabezadoTabla[]={"DNI","Nombre","Apellido Paterno","Apellido Materno","Género","Telefono","Correo","Fecha de nacimiento","Dirección"}; //para cambiar los nombres de la tabla que estan por defecto
        MiTabla = new DefaultTableModel(null,EncabezadoTabla);
        tblFiltro.setModel(MiTabla);
    }
    
    public void MostrarRegistroTabla(){ //Para que muestre los registros
        Mostrar();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFiltroContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFiltroContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFiltroContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFiltroContactos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFiltroContactos().setVisible(true);
            }
        });
    }
    private void Limpiesa(){//se encarga de borrar los datos que aparecen en la tabla pero no los datos guardados
        DefaultTableModel temp = (DefaultTableModel) tblFiltro.getModel();
        int filas = tblFiltro.getRowCount();

        for (int a = 0; filas > a; a++) {
            temp.removeRow(0);
        }
    }
    
    private void Mostrar(){
        try{
            Connection conex = null; //llama la conexion
            DefaultTableModel dTabla = (DefaultTableModel)tblFiltro.getModel();
            cConnection conectando = new cConnection(); //llama la clase cConnection
            conex = conectando.getConnection();//retorna conexion
            String Registro[] = new String[10]; //aca el numero lo modificas segun la cantidad de columnas
            String SQL = "Select * from datos"; //sentencia sql para llamar los registros
            Statement sentencia = conex.createStatement(); //crea la sentencia sql
            ResultSet rst = sentencia.executeQuery(SQL); //ejecuta la consulta de la sentencia sql
            while(rst.next()){
                Registro[0] = rst.getString("DNI"); //el numero y el nombre que esta en tu BD, en este caso access, se comienza desde cero
                Registro[1] = rst.getString("Nombre"); 
                Registro[2] = rst.getString("ApellidoPaterno");
                Registro[3] = rst.getString("ApellidoMaterno");
                Registro[4] = rst.getString("Genero"); 
                Registro[5] = rst.getString("Telefono");
                Registro[6] = rst.getString("Correo");
                Registro[7] = rst.getString("FechaNacimiento");
                Registro[8] = rst.getString("Direccion");
                dTabla.addRow(Registro); //Agrega a cada columna
            }
            tblFiltro.setModel(dTabla); //para llamar nuestra tabla
        } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Se ha producido un error al cargar los datos - " + e);//mensaje de error y el problema a resolver
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnMujeres;
    private javax.swing.JButton btnVarones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFiltro;
    private javax.swing.JButton tbnRegresar;
    // End of variables declaration//GEN-END:variables
}
